// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowPlatform.Api.Data;

#nullable disable

namespace WorkflowPlatform.Api.Migrations
{
    [DbContext(typeof(WorkflowPlatformDbContext))]
    [Migration("20260813012858_CompositeNodeKey")]
    partial class CompositeNodeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkflowInstanceCurrentNodes", b =>
                {
                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkflowInstanceId", "NodeId", "WorkflowDefinitionId");

                    b.HasIndex("NodeId", "WorkflowDefinitionId");

                    b.ToTable("WorkflowInstanceCurrentNodes", (string)null);
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.Connection", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConditionExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConnectionId");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("SourceNodeId", "WorkflowDefinitionId");

                    b.HasIndex("TargetNodeId", "WorkflowDefinitionId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.Node", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("NodeId", "WorkflowDefinitionId");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.NodeExecution", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluationOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("NodeId", "WorkflowDefinitionId");

                    b.ToTable("NodeExecutions");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.TaskHandlerReference", b =>
                {
                    b.Property<Guid>("TaskHandlerReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalMetadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlerType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TaskHandlerReferenceId");

                    b.HasIndex("NodeId", "WorkflowDefinitionId")
                        .IsUnique();

                    b.ToTable("TaskHandlerReferences");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("DefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("DefinitionId");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.WorkflowInstance", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InstanceId");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("WorkflowInstanceCurrentNodes", b =>
                {
                    b.HasOne("WorkflowPlatform.Api.Domain.WorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowPlatform.Api.Domain.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId", "WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.Connection", b =>
                {
                    b.HasOne("WorkflowPlatform.Api.Domain.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Connections")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowPlatform.Api.Domain.Node", "SourceNode")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("SourceNodeId", "WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkflowPlatform.Api.Domain.Node", "TargetNode")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("TargetNodeId", "WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.Node", b =>
                {
                    b.HasOne("WorkflowPlatform.Api.Domain.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.NodeExecution", b =>
                {
                    b.HasOne("WorkflowPlatform.Api.Domain.WorkflowInstance", "WorkflowInstance")
                        .WithMany("ExecutionHistory")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowPlatform.Api.Domain.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId", "WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.TaskHandlerReference", b =>
                {
                    b.HasOne("WorkflowPlatform.Api.Domain.Node", "Node")
                        .WithOne()
                        .HasForeignKey("WorkflowPlatform.Api.Domain.TaskHandlerReference", "NodeId", "WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.WorkflowInstance", b =>
                {
                    b.HasOne("WorkflowPlatform.Api.Domain.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.Node", b =>
                {
                    b.Navigation("IncomingConnections");

                    b.Navigation("OutgoingConnections");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.WorkflowDefinition", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("WorkflowPlatform.Api.Domain.WorkflowInstance", b =>
                {
                    b.Navigation("ExecutionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
